init:
  - git config --global core.autocrlf input
  
image: 
  - Visual Studio 2017

cache:
  - src\packages -> **\packages.config
  - tools -> build.cake

build_script: 
  - ps: .\build.ps1

after_build:
  - ps: $env:ARTIFACT_NAME = if($env:APPVEYOR_REPO_TAG_NAME){$env:APPVEYOR_REPO_TAG_NAME} else {"$($env:APPVEYOR_REPO_COMMIT)-pre"}

artifacts: 
  - path: artifacts\*
    name: SwashbuckleAspNetVersioningShim_%ARTIFACT_NAME%

deploy:
  - provider: GitHub
    description: Release of SwashbuckleAspNetVersioningShim version %ARTIFACT_NAME%
    auth_token:
      secure: 5lhtYmrK8GyagLOZFAIKcCnLrYU62nz3nYYwdb4xWobiTmZ92qfAn3+7g+kmasCf
    artifact: /.*\.nupkg/
    draft: false
    prerelease: true
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: NuGet
    server: https://www.myget.org/F/rh072005/api/v2/package
    api_key:
      secure: xslJdZlEXsrdzucocErMW6yYuLA4rkFLpnrSHGS7AS0rHwvq5ZkxW4l28RVOJiwI
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: zUyeNr+QR1B7tT4uFyk36oJG58k8tZZDZEznTpEWygmfG8UJgBphkgD6FsvNIYyi
    on:
      branch: master
      appveyor_repo_tag: true

test: off
